version: 2
updates:
  # Dependabot for service-protos directory
  - package-ecosystem: npm
    directory: "/service-protos"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - dependabot

  # Dependabot for user-service directory
  - package-ecosystem: npm
    directory: "/user-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - dependabot
